### ISSUE TITLE
v2.6.10 not working with list of objects as a entity

### ISSUE THREAD

**Issue by sahilgupta202** [spring-projects/spring-data-keyvalue#488] opened 2023-03-21 12:51 UTC
We have recently upgraded our application from spring boot 2.1.6.RELEASE to 2.6.14. Along with it, we also upgraded `spring-boot-starter-data-jpa` to be compliant with spring-boot which bring in upgrade of these two libraries 
`
- **org.springframework.data:spring-data-keyvalue** from 2.1.9 to 2.6.10
- **org.springframework.data:spring-data-commons** from 2.1.9 to 2.6.10
`

We are creating a KeyValueRepository in an application backed by a hazelcast entity (we are using v3.12 for hazelcast)

```
//Creating an hazelcast entity with value as List of employees and key as a employeeId
@HazelcastEntity(backingStoreMapStoreClass = EmployeeCacheLoader::class)
interface TraderRepository : KeyValueRepository<List<EmployeeDetails>, String>

//EmployeeCacheLoader implementation
class TraderCacheLoader() : MapStore<String, List<EmployeeDetails>>() {

  override fun load(employeeId: String): List<EmployeeDetails> {
      //implementation to load an employee
   }

   override fun loadAll(requestList: Collection<String>): Map<String, List<EmployeeDetails>> {
      //implementation to load all
   }
}
```

This used to work correctly without any errors with spring-data-keyvalue v2.1.9 but it is not working with v2.6.10 and throwing this error,

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeRepository' defined in com.lab49.ca.salesandtrading.cache.EmployeerRepository defined in @EnableHazelcastRepositories declared on GenericRfqApp: Invocation of init method failed; nested exception is

 java.lang.IllegalArgumentException: Entity must not be 'null'.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:936)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:423)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.lab49.ca.ionapp.spring.ion20.ION20SpringApplicationModule$SpringApplicationService$1.onSuccess(ION20SpringApplicationModule.java:162)
	at com.lab49.ca.ionapp.spring.ion20.ION20SpringApplicationModule$SpringApplicationService$1.onSuccess(ION20SpringApplicationModule.java:127)
	at com.iontrading.isf.commons.async.impl.a$1.run(AsyncResultPromiseImpl.java:131)
	at com.iontrading.isf.executors.impl.monitoring.g.run(MonitoredRunnable.java:18)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Entity must not be 'null'.
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.data.hazelcast.repository.support.HazelcastRepositoryFactory.getEntityInformation(HazelcastRepositoryFactory.java:91)
	at org.springframework.data.keyvalue.repository.support.KeyValueRepositoryFactory.getTargetRepository(KeyValueRepositoryFactory.java:132)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:325)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:231)
	at org.springframework.data.util.Lazy.get(Lazy.java:115)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:329)
	at org.springframework.data.keyvalue.repository.support.KeyValueRepositoryFactoryBean.afterPropertiesSet(KeyValueRepositoryFactoryBean.java:135)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 19 more
```

After debugging it, we found that the the below code is giving as null as there is no mapping context created by **spring-data-keyvalue** for java.util.List which was not the case earlier. 

```
//domainClass will be java.util.List
PersistentEntity<T, ?> entity = (PersistentEntity<T, ?>) keyValueOperations.getMappingContext()
      .getPersistentEntity(domainClass)
```

Is there any way to fix this after the upgrade?

We have tried debugging the old and new implementation of the **spring-data-keyvalue** libray and found that the implementation is changed for some reason. So either we donot support it now or there is a way to support it.

NEW IMPLEMENTATION (v2.6.10)

```
File Name: AbstractMappingContext.java

//code
Line 178: if (!this.shouldCreatePersistentEntityFor(type) is returing true and hence the result

//In this function the java.util.list is treated as a simple type which seems wrong to me
protected boolean shouldCreatePersistentEntityFor(TypeInformation<?> type) {
    if (this.simpleTypeHolder.isSimpleType(type.getType())) {
      return false; //it reaches here
    } else if (NullableWrapperConverters.supports(type.getType())) {
      return false;
    } else {
      return !KotlinDetector.isKotlinType(type.getType()) || KotlinReflectionUtils.isSupportedKotlinClass(type.getType());
    }
  }
```

OLD IMPLEMENTATION

```
//This function returns true and hence there is a mapping contecxt added for that domain type
protected boolean shouldCreatePersistentEntityFor(TypeInformation<?> type) {
    if (this.simpleTypeHolder.isSimpleType(type.getType())) {
      return false;
    } else {
      return !org.springframework.data.util.ReflectionUtils.isKotlinClass(type.getType()) || org.springframework.data.util.ReflectionUtils.isSupportedKotlinClass(type.getType());
    }
  }

```

**Comment by jxblum** [comment] 2023-04-05 23:35
Hi @sahilgupta202 -

First, I'd like to point out that even Spring Boot `2.6`, along with Spring Data `2.6`, are now Open Source Software (OSS) End-of-Life (EOL)! 

You can review both the OSS and commercial support timelines at [spring.io](https://spring.io). For instance, Spring Boot support timelines can be found [here](https://spring.io/projects/spring-boot#support).

As you can, OSS support for Spring Boot `2.6` ended on November 24th, 2022. While commercial support extends until February 24th, 2024, it does require you to obtain a VMware Spring Runtime (VSR) license (see [here](https://tanzu.vmware.com/spring-runtime)).

I would highly recommend that you move to the latest version of Spring Boot/Spring Data `2.7.x`. Spring Boot `2.7.x` is currently at version `2.7.10`. Additionally both Spring Boot and Spring Data `2.x` is based on Java 8. Spring Boot `3.0.x` and Spring Data `3.0.x` are the latest GA versions currently available, but are based on Java 17. I would even encourage you to consider moving to Spring Boot/Spring Data 3 if Java 17 with Jakarta EE 9/10 along with Spring Framework 6, would not impose any issues for you and your team, or Spring (Boot/Data) based project.

Spring Data support for Hazelcast is provided by Hazelcast since [Spring Data Hazelcast](https://github.com/hazelcast/spring-data-hazelcast) is a community module (see "_Community modules_" on this [page](https://spring.io/projects/spring-data)).

Continued...

**Comment by jxblum** [comment] 2023-04-06 01:08
In continuation...

Having mentioned the information in my previous comment above, _Spring Data Hazelcast_ does build on _Spring Data KeyValue_. However, most of the details of this problem originate in _Spring Data Commons_, technically, as can be seen in the _Stack Trace_, notably here:

```java
	at org.springframework.data.hazelcast.repository.support.HazelcastRepositoryFactory.getEntityInformation(HazelcastRepositoryFactory.java:91)
	at org.springframework.data.keyvalue.repository.support.KeyValueRepositoryFactory.getTargetRepository(KeyValueRepositoryFactory.java:132)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:325)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323)
```

Even the code reference you shared above, involving the `AbstractMappingContext`, is a class from _Spring Data Commons_, ([Javadoc](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/mapping/context/AbstractMappingContext.html) and [source](https://github.com/spring-projects/spring-data-commons/blob/2.7.10/src/main/java/org/springframework/data/mapping/context/AbstractMappingContext.java)).

> TIP: As you are probably aware, _Spring Data Commons_ is the common core data access framework for all Spring Data modules, like _Spring Data Hazelcast_. In-between _Spring Data Commons_ and _Spring Data Hazelcast_ lies _Spring Data KeyValue_, which provides a framework for key-value data structure based stores, such as Hazelcast and Redis, using _Spring Data Redis_.

We can see that the root cause of the Exception comes from Hazelcast, [here](https://github.com/hazelcast/spring-data-hazelcast/blob/v2.4.0/src/main/java/org/springframework/data/hazelcast/repository/support/HazelcastRepositoryFactory.java#L91).

In order to understand why the `PersistentEntity` was `null`, we must look to this [line](https://github.com/hazelcast/spring-data-hazelcast/blob/v2.4.0/src/main/java/org/springframework/data/hazelcast/repository/support/HazelcastRepositoryFactory.java#L89-L90), where _Spring Data Hazelcast_ is trying to get the `PersistentEntity` declared in the Spring application `Repository` interface declaration, which in your case is the `TraderRepository`. The domain type declaration in your _Repository_ signature, from:

```java
interface TraderRepository : KeyValueRepository<List<EmployeeDetails>, String>
```

Is a `List` of `EmployDetails` objects. The ID is a `String`. See [Javadoc](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/Repository.html) for the _Spring Data Commons'_ `Repository` interface.

It is uncommon for the (persistent) "entity" of a _Repository_ to be a Collection-type, or an array type (e.g. 
 EmployeeDetails[]`). You should simply be accessing and operating on the `EmployeeDetails` application domain model type itself as the entity to persists or access using a Spring Data _Repository_.

There is nothing particularly interesting about _Spring Data KeyValue's_  `KeyValueMappingContext` class ([source](https://github.com/spring-projects/spring-data-keyvalue/blob/2.7.10/src/main/java/org/springframework/data/keyvalue/core/mapping/context/KeyValueMappingContext.java)). So in fact, the `getPersistentEntity(..)` [call](https://github.com/hazelcast/spring-data-hazelcast/blob/v2.4.0/src/main/java/org/springframework/data/hazelcast/repository/support/HazelcastRepositoryFactory.java#L89-L90) (originating from _Spring Data Hazelcast_) on the `MappingContext` implementation from _Spring Data KeyValue_ actually comes from the `AbstractMappingContext` from _Spring Data Commons_. See [here](https://github.com/spring-projects/spring-data-commons/blob/2.7.10/src/main/java/org/springframework/data/mapping/context/AbstractMappingContext.java#L203-L210) then [here](https://github.com/spring-projects/spring-data-commons/blob/2.7.10/src/main/java/org/springframework/data/mapping/context/AbstractMappingContext.java#L251-L292).

The real question is, should the domain type (i.e. `List<EmployeeDetails>`) be something the Spring Data Repository infrastructure can handle? ([This logic](https://github.com/spring-projects/spring-data-commons/blob/2.7.10/src/main/java/org/springframework/data/mapping/context/AbstractMappingContext.java#L275)).

If we drill down into the implementation of the `shouldCreatePersistentEntityFor(..)` method, we will see the implementation [here](https://github.com/spring-projects/spring-data-commons/blob/2.7.10/src/main/java/org/springframework/data/mapping/context/AbstractMappingContext.java#L522-L542).

This [call](https://github.com/spring-projects/spring-data-commons/blob/2.7.10/src/main/java/org/springframework/data/mapping/context/AbstractMappingContext.java#L533), delegates back to _Spring Data KeyValue's_ `SimplyTypeHolder` implementation, [here](https://github.com/spring-projects/spring-data-keyvalue/blob/2.7.10/src/main/java/org/springframework/data/keyvalue/core/mapping/context/KeyValueMappingContext.java#L78-L86).

As you can see, all `java.util` types are considered a "simple type" and not a persistent entity type, resulting in this [condition](https://github.com/spring-projects/spring-data-commons/blob/2.7.10/src/main/java/org/springframework/data/mapping/context/AbstractMappingContext.java#L533) being `false`.

`SimplyTypes` are NOT `PersistentEntities`.

This was logic was put into effect as of Issue #374.

To be continued...

**Comment by jxblum** [comment] 2023-04-08 00:28
In conclusion...

I'd strongly argue against using Collection or array types as persistent entities in Spring Data _Repository_ infrastructure.

Spring Data _Repository_ declarations, and extensions of the `Repository` or `CrudRepository` interfaces, are  typed to single application domain types,  persistable as entities.

Additionally, Spring Data's `CrudRepository` interface even defines data access operations to get a Collection of entities, such as `findAll()` ([Javadoc](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#findAll())) or `findAllById(..)` ([Javadoc](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#findAllById(java.lang.Iterable))) and even save a Collection of entities with `saveAll(:Iterable<T>)` ([Javadoc](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#saveAll(java.lang.Iterable))).

Furthermore, if you need `List` specific operations, then there is the `ListCrudRepository` interface ([Javadoc](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/ListCrudRepository.html)), and extensions for sorting and paging, since Spring Data `3.0`.

However, if you must persist or access a Collection or array like entity as if it were a single (persistent) entity, then you could extend the `KeyValueMappingContext` and declare an application-specific `MappingContext` implementation, that allows Collections (e.g. `Lists`) or array type domain types to be declared and handled by the Spring Data _Repository_ infrastructure.

You would register your custom, application-specific `MappingContext` implementation as a bean in the Spring `ApplicationContext` and specifically name it "_keyValueMappingContext_" (see [here](https://github.com/spring-projects/spring-data-keyvalue/blob/2.7.10/src/main/java/org/springframework/data/keyvalue/repository/config/KeyValueRepositoryConfigurationExtension.java#L204-L214) and then [here](repository)).

For example:

```java
@Configuration
class MyApplicationConfiguration {

  @Bean
  KeyValueMappingContext keyValueMappingContext() {
    // instantiate your custom, application-specific `MappingContext` object here
  }
```

Your custom, application-specific `MappingContext` could even extend the Spring Data KeyValue's `KeyValueMappingContext` implementation ([source](https://github.com/spring-projects/spring-data-keyvalue/blob/2.7.10/src/main/java/org/springframework/data/keyvalue/core/mapping/context/KeyValueMappingContext.java)) as your base class and you can supply your own `SimpleTypeHolder`.

**Comment by jxblum** [comment] 2023-04-08 00:34
Given my analysis and feedback above, this ask is not recommended and not something that Spring Data should support.

**Closed** 2023-04-11 14:56 UTC
Labels: status: declined, in: repository, status: invalid, status: feedback-provided
