### ISSUE TITLE
Invalid error message in case of null id in the findById method

### ISSUE THREAD

**Issue by mhewedy** [spring-projects/spring-data-keyvalue#344] opened 2021-01-05 19:30 UTC
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem

The error message in `KeyValueTemplate.findById(…)` reports a message that doestn't match the intended action:

https://github.com/spring-projects/spring-data-keyvalue/blob/c84c309278d15f5ad36ef2f9d5be76ddb7e04769/src/main/java/org/springframework/data/keyvalue/core/KeyValueTemplate.java#L259

## Solution

Update the exception message so it no longer talks about inserted objects but reports a more appropriate message or aligns with the general convention `… must not be null!`.

## Steps to Fix

- [ ] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by AbassAdeyemi** [comment] 2021-01-12 08:16
I would love to claim this issue.

**Comment by mp911de** [comment] 2021-01-12 08:52
Great, @AbassAdeyemi the issue is yours and please let us know if you have any questions.

**Comment by mp911de** [comment] 2021-01-13 08:04
Fixed via #345.

**Closed by mp911de** 2021-01-13 08:04 UTC
Labels: type: bug
